language: objective-c
compiler:
  - clang
before_install:
  - brew update
  - brew install md5sha1sum
  - brew install xz
  - brew install lcov
  - brew install gettext
  - brew install fftw
  - brew install boost
  - brew install cppunit
  - brew install gsl
  - which automake
  - automake --version
  - which autoconf
  - autoconf --version
  - which autoreconf
  - autoreconf --version
script:
- "( git fetch --unshallow ; true )"
- ls -l
- ./reconf
- ls -l
- git describe --always
- ./configure
- make
- make check VERBOSE=yes
